In [1]:
#  import required libraries

import os
import numpy as np
import pandas as pd
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_curve, auc, roc_auc_score


In [2]:
df = pd.read_csv('energydata_complete.csv')

In [3]:
df.sample(5)

date  Appliances  lights         T1       RH_1  \
6205   2016-02-23 19:10:00         110      10  21.200000  42.266667   
9484   2016-03-17 13:40:00          50       0  22.323333  34.363333   
17616  2016-05-13 01:00:00          50       0  25.200000  48.500000   
13178  2016-04-12 05:20:00          40       0  21.790000  42.863333   
6727   2016-02-27 10:10:00          50       0  19.790000  39.526667   

              T2       RH_2         T3       RH_3     T4  ...         T9  \
6205   19.390000  42.466667  21.033333  40.326667  21.50  ...  18.290000   
9484   21.500000  33.400000  21.500000  34.590000  21.89  ...  19.890000   
17616  23.405714  49.805714  26.566667  44.530000  25.20  ...  24.200000   
13178  19.133333  45.563333  23.356667  40.363333  21.79  ...  20.823333   
6727   18.760000  39.066667  20.290000  37.290000  20.29  ...  17.890000   

            RH_9      T_out  Press_mm_hg     RH_out  Windspeed  Visibility  \
6205   39.590000   3.866667   759.200000  87.166667   1.000000   40.000000   
9484   37.500000   9.566667   765.533333  52.333333   4.666667   24.000000   
17616  47.790000  15.100000   745.900000  94.000000   3.000000   45.000000   
13178  44.766667   6.233333   751.600000  91.666667   1.000000   40.000000   
6727   38.693333   3.250000   751.000000  69.166667   6.000000   26.666667   

       Tdewpoint        rv1        rv2  
6205    1.950000  10.498350  10.498350  
9484    0.233333  24.145988  24.145988  
17616  14.200000  29.440170  29.440170  
13178   5.000000  13.878124  13.878124  
6727   -2.033333  43.495458  43.495458  

[5 rows x 29 columns]

In [4]:
df.shape

(19735, 29)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   date         19735 non-null  object 
 1   Appliances   19735 non-null  int64  
 2   lights       19735 non-null  int64  
 3   T1           19735 non-null  float64
 4   RH_1         19735 non-null  float64
 5   T2           19735 non-null  float64
 6   RH_2         19735 non-null  float64
 7   T3           19735 non-null  float64
 8   RH_3         19735 non-null  float64
 9   T4           19735 non-null  float64
 10  RH_4         19735 non-null  float64
 11  T5           19735 non-null  float64
 12  RH_5         19735 non-null  float64
 13  T6           19735 non-null  float64
 14  RH_6         19735 non-null  float64
 15  T7           19735 non-null  float64
 16  RH_7         19735 non-null  float64
 17  T8           19735 non-null  float64
 18  RH_8         19735 non-null  float64
 19  T9  

In [6]:
df.isnull().sum()

date           0
Appliances     0
lights         0
T1             0
RH_1           0
T2             0
RH_2           0
T3             0
RH_3           0
T4             0
RH_4           0
T5             0
RH_5           0
T6             0
RH_6           0
T7             0
RH_7           0
T8             0
RH_8           0
T9             0
RH_9           0
T_out          0
Press_mm_hg    0
RH_out         0
Windspeed      0
Visibility     0
Tdewpoint      0
rv1            0
rv2            0
dtype: int64

In [7]:
df.round(2).head()

date  Appliances  lights     T1   RH_1    T2   RH_2     T3  \
0  2016-01-11 17:00:00          60      30  19.89  47.60  19.2  44.79  19.79   
1  2016-01-11 17:10:00          60      30  19.89  46.69  19.2  44.72  19.79   
2  2016-01-11 17:20:00          50      30  19.89  46.30  19.2  44.63  19.79   
3  2016-01-11 17:30:00          50      40  19.89  46.07  19.2  44.59  19.79   
4  2016-01-11 17:40:00          60      40  19.89  46.33  19.2  44.53  19.79   

    RH_3     T4  ...     T9   RH_9  T_out  Press_mm_hg  RH_out  Windspeed  \
0  44.73  19.00  ...  17.03  45.53   6.60        733.5    92.0       7.00   
1  44.79  19.00  ...  17.07  45.56   6.48        733.6    92.0       6.67   
2  44.93  18.93  ...  17.00  45.50   6.37        733.7    92.0       6.33   
3  45.00  18.89  ...  17.00  45.40   6.25        733.8    92.0       6.00   
4  45.00  18.89  ...  17.00  45.40   6.13        733.9    92.0       5.67   

   Visibility  Tdewpoint    rv1    rv2  
0       63.00        5.3  13.28  13.28  
1       59.17        5.2  18.61  18.61  
2       55.33        5.1  28.64  28.64  
3       51.50        5.0  45.41  45.41  
4       47.67        4.9  10.08  10.08  

[5 rows x 29 columns]

In [8]:
df.describe().round(2)

Appliances    lights        T1      RH_1        T2      RH_2        T3  \
count    19735.00  19735.00  19735.00  19735.00  19735.00  19735.00  19735.00   
mean        97.69      3.80     21.69     40.26     20.34     40.42     22.27   
std        102.52      7.94      1.61      3.98      2.19      4.07      2.01   
min         10.00      0.00     16.79     27.02     16.10     20.46     17.20   
25%         50.00      0.00     20.76     37.33     18.79     37.90     20.79   
50%         60.00      0.00     21.60     39.66     20.00     40.50     22.10   
75%        100.00      0.00     22.60     43.07     21.50     43.26     23.29   
max       1080.00     70.00     26.26     63.36     29.86     56.03     29.24   

           RH_3        T4      RH_4  ...        T9      RH_9     T_out  \
count  19735.00  19735.00  19735.00  ...  19735.00  19735.00  19735.00   
mean      39.24     20.86     39.03  ...     19.49     41.55      7.41   
std        3.25      2.04      4.34  ...      2.01      4.15      5.32   
min       28.77     15.10     27.66  ...     14.89     29.17     -5.00   
25%       36.90     19.53     35.53  ...     18.00     38.50      3.67   
50%       38.53     20.67     38.40  ...     19.39     40.90      6.92   
75%       41.76     22.10     42.16  ...     20.60     44.34     10.41   
max       50.16     26.20     51.09  ...     24.50     53.33     26.10   

       Press_mm_hg    RH_out  Windspeed  Visibility  Tdewpoint       rv1  \
count     19735.00  19735.00   19735.00    19735.00   19735.00  19735.00   
mean        755.52     79.75       4.04       38.33       3.76     24.99   
std           7.40     14.90       2.45       11.79       4.19     14.50   
min         729.30     24.00       0.00        1.00      -6.60      0.01   
25%         750.93     70.33       2.00       29.00       0.90     12.50   
50%         756.10     83.67       3.67       40.00       3.43     24.90   
75%         760.93     91.67       5.50       40.00       6.57     37.58   
max         772.30    100.00      14.00       66.00      15.50     50.00   

            rv2  
count  19735.00  
mean      24.99  
std       14.50  
min        0.01  
25%       12.50  
50%       24.90  
75%       37.58  
max       50.00  

[8 rows x 28 columns]

In [9]:
df.duplicated().sum()

0

In [10]:
df = df.drop(columns = ['date','lights'])

In [11]:
df.head()

Appliances     T1       RH_1    T2       RH_2     T3       RH_3         T4  \
0          60  19.89  47.596667  19.2  44.790000  19.79  44.730000  19.000000   
1          60  19.89  46.693333  19.2  44.722500  19.79  44.790000  19.000000   
2          50  19.89  46.300000  19.2  44.626667  19.79  44.933333  18.926667   
3          50  19.89  46.066667  19.2  44.590000  19.79  45.000000  18.890000   
4          60  19.89  46.333333  19.2  44.530000  19.79  45.000000  18.890000   

        RH_4         T5  ...         T9   RH_9     T_out  Press_mm_hg  RH_out  \
0  45.566667  17.166667  ...  17.033333  45.53  6.600000        733.5    92.0   
1  45.992500  17.166667  ...  17.066667  45.56  6.483333        733.6    92.0   
2  45.890000  17.166667  ...  17.000000  45.50  6.366667        733.7    92.0   
3  45.723333  17.166667  ...  17.000000  45.40  6.250000        733.8    92.0   
4  45.530000  17.200000  ...  17.000000  45.40  6.133333        733.9    92.0   

   Windspeed  Visibility  Tdewpoint        rv1        rv2  
0   7.000000   63.000000        5.3  13.275433  13.275433  
1   6.666667   59.166667        5.2  18.606195  18.606195  
2   6.333333   55.333333        5.1  28.642668  28.642668  
3   6.000000   51.500000        5.0  45.410389  45.410389  
4   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 27 columns]

In [12]:
X = df.drop('Appliances', axis = 1)
y = df['Appliances']

In [13]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(X,y,test_size = 0.3, random_state = 42)

In [19]:
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

(13814, 26)
(5921, 26)
(13814,)
(5921,)


In [14]:
from sklearn.preprocessing import MinMaxScaler

In [15]:
scaler = MinMaxScaler()
xtrain_scaled = scaler.fit_transform(xtrain)
xtest_scaled = scaler.transform(xtest)

In [16]:
print(xtest_scaled)

[[0.43294615 0.27554825 0.12066877 ... 0.3        0.51234794 0.51234794]
 [0.53854277 0.85778509 0.37727163 ... 0.35454545 0.46937859 0.46937859]
 [0.48574446 0.27883772 0.11146111 ... 0.19090909 0.00259746 0.00259746]
 ...
 [0.43681802 0.40712719 0.18899927 ... 0.51742424 0.79266914 0.79266914]
 [0.55015839 0.46732456 0.33438333 ... 0.52272727 0.60824256 0.60824256]
 [0.43294615 0.50219298 0.21322995 ... 0.74393939 0.19877963 0.19877963]]


## model building

In [21]:
from sklearn.linear_model import LinearRegression
classifier = LinearRegression()
classifier.fit(xtrain,ytrain) 

LinearRegression()

In [22]:
ypred_test = classifier.predict(xtest)
ypred_train = classifier.predict(xtrain)

In [25]:
from sklearn.metrics import mean_absolute_error as mae

In [30]:
# MAE Computation
from sklearn.metrics import mean_squared_error as MSE


maerror = mae(ytest, ypred_test)
print("mae : % f" %(maerror))

mae :  53.642978


In [24]:
# RMSE Computation
from sklearn.metrics import mean_squared_error as MSE


rmse = np.sqrt(MSE(ytest, ypred_test))
print("RMSE : % f" %(rmse))

RMSE :  93.640461


In [32]:
from sklearn.linear_model import Lasso
classifier = Lasso()
classifier.fit(xtrain,ytrain) 

Lasso()

In [33]:
ypred_test = classifier.predict(xtest)
ypred_train = classifier.predict(xtrain)

In [34]:
# RMSE Computation
from sklearn.metrics import mean_squared_error as MSE


rmse = np.sqrt(MSE(ytest, ypred_test))
print("RMSE : % f" %(rmse))

RMSE :  93.892498
